# Generated by Django 3.2.9 on 2022-05-22 18:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ingredient Name')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('units', models.CharField(max_length=255, verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.CharField(max_length=255, verbose_name='Starus')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reciepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.CharField(max_length=255, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('video', models.TextField(verbose_name='Video Link')),
                ('category', models.CharField(choices=[('Dinner', 'Dinner'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Salad', 'Salad'), ('Soup', 'Soup'), ('Meat', 'Meat'), ('Fish', 'Fish'), ('Drink', 'Drink')], max_length=255, verbose_name='Category')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userprofile', verbose_name='Author')),
                ('ingredients', models.ManyToManyField(to='main.Ingredient', verbose_name='Ingredient')),
            ],
            options={
                'verbose_name': 'Reciepe',
                'verbose_name_plural': 'Reciepes',
            },
        ),
    ]
